services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    environment:
      - PORT=3000
      - UPS_API_BASE_URL=${UPS_API_BASE_URL}
      - UPS_OAUTH_TOKEN_URL=${UPS_OAUTH_TOKEN_URL}
      - UPS_CLIENT_ID=${UPS_CLIENT_ID}
      - UPS_CLIENT_SECRET=${UPS_CLIENT_SECRET}
    ports:
      - "3000:3000"

  integration-tests:
    build:
      context: .
      dockerfile: docker/Dockerfile.tests
    environment:
      - UPS_API_BASE_URL=${UPS_API_BASE_URL}
      - UPS_OAUTH_TOKEN_URL=${UPS_OAUTH_TOKEN_URL}
      - UPS_CLIENT_ID=${UPS_CLIENT_ID}
      - UPS_CLIENT_SECRET=${UPS_CLIENT_SECRET}
    depends_on:
      - backend
